{% set name = "s3fs" %}
{% set version = "2023.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/s3fs-{{ version }}.tar.gz
  sha256: 963ee2e070e03e2952d535dbc6fd2b341869fcd16006cf74b90bcf39fd26cded

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - aiobotocore >=2.4.2,<2.4.3
    - aiohttp
    - fsspec ==2023.3.0
    - python >=3.8

test:
  imports:
    - s3fs
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://s3fs.readthedocs.io/en/latest/
  summary: Convenient Filesystem interface over S3
  license: BSD-3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/dask/s3fs
  doc_url: https://s3fs.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - tomaugspurger
